### ISSUE TITLE
REQUIRE file needs SpecialFunctions.

### ISSUE THREAD

**Issue by BlakeList** [ericproffitt/TopicModelsVB.jl#15]
Importation results in an error as "Package TopicModelsVB does not have SpecialFunctions in its dependencies". 

Change REQUIRE from:

`julia 0.6`
`Distributions`
`OpenCL`

to:

`julia 0.6`
`Distributions`
`OpenCL`
`SpecialFunctions`

Cheers,
Blake

**Comment by ericproffitt** [comment]
should be fixed now with new version of package.
