### ISSUE TITLE
files not found

### ISSUE THREAD

**Issue by vsaase** [ericproffitt/TopicModelsVB.jl#17]
https://github.com/ericproffitt/TopicModelsVB.jl/blob/e2c61cfded7756d3f1f1ae621b6448e78e882cda/src/Corpus.jl#L318

Hi, 
the path is not necessarily right. In my case it is /home/vsaase/.julia/dev/TopicModelsVB/datasets
Maybe something like `joinpath(@__DIR__, "../datasets")`

**Comment by ericproffitt** [comment]
Thanks for finding this, should be fixed now.
