### ISSUE TITLE
How to detect topic?

### ISSUE THREAD

**Issue by kannadaraj** [ericproffitt/TopicModelsVB.jl#2]
Thanks very much for developing such a simple tool. This is easy to follow and use.  The tutorial is very lucid.
But i have a question i couldn't find a way to detect topic fro unseen documents using a developed. Please can you help help me how to do extract the topic for some new random text. Thanks very much.

KR

**Comment by esproff** [comment]
Hi KR,

I think this might be doable, give me like a week to work on it and I'll get back to you with a solution (hopefully).

**Comment by kannadaraj** [comment]
Thanks very much for the reply.

**Comment by kannadaraj** [comment]
Sorry to bug you again.. Are there any more updates.. thanks very much,...

KR

**Comment by esproff** [comment]
Hi KR,

Apologies I've been extremely busy, it's probably going to take me another 2-3 weeks before I have time to add this functionality.

**Comment by janekdb** [comment]
I am also interested in this.

**Comment by esproff** [comment]
I just wanted to let you know I haven't forgotten about this functionality, I haven't had a free day yet to work on it, but it's coming!

**Comment by ericproffitt** [comment]
It took me quite a bit longer than I had originally anticipated to add this functionality (3 years!).
