### ISSUE TITLE
How do save topics to array. Showtopics() => some variables

### ISSUE THREAD

**Issue by ValeriiBaidin** [ericproffitt/TopicModelsVB.jl#23]
Would you suggest, how use result from showtopics() later in the code?

thank you in advance.

**Comment by ericproffitt** [comment]
Hi Valerii,

Sure, so the field you want is `model.topics`.

This will be of type `Array{Array{Int64,1},1}` (basically a vector of vectors), where each vector corresponds to the (descending) ranking of vocabulary keys for its corresponding topic.

**Comment by ValeriiBaidin** [comment]
> Hi Valerii,
> 
> Sure, so the field you want is `model.topics`.
> 
> This will be of type `Array{Array{Int64,1},1}` (basically a vector of vectors), where each vector corresponds to the (descending) ranking of vocabulary keys for its corresponding topic.

Thank you, 
I am sorry to bother you since I  didn't found it.
