### ISSUE TITLE
Does it have the functionality to reduce vocabulary size?

### ISSUE THREAD

**Issue by ValeriiBaidin** [ericproffitt/TopicModelsVB.jl#26]
Does it have the functionality to reduce vocabulary size?
For instance, keep only the top 10000 words. OR Remove words incurred less than K documents. 

Thank you in advance.

**Comment by ericproffitt** [comment]
So there isn't currently functionaltiy for keeping the top N words. However you can remove all words that appear less than or equal to N times in the corpus by doing,

```julia
abridge_corp!(corp)
fixcorp!(corp)
```
