### ISSUE TITLE
What is the fields model.topics? Is it possible to get highly probable doc for each topics?

### ISSUE THREAD

**Issue by ValeriiBaidin** [ericproffitt/TopicModelsVB.jl#29]
What is the field model.topics? Is it possible to get a highly probable doc for each topic?

Thank you in advance.

**Comment by ericproffitt** [comment]
`model.topics` is the ranking of the `corp.vocab` keys for each topic.

For getting highly probable documents for a topic, you want to look at the `topicdist` of the document.

There is no functionality or data which ranks the documents for each topic.

**Comment by ValeriiBaidin** [comment]
> `model.topics` is the ranking of the `corp.vocab` keys for each topic.
> 
> For getting highly probable documents for a topic, you want to look at the `topicdist` of the document.
> 
> There is no functionality or data which ranks the documents for each topic.

thank you so much
