### ISSUE TITLE
why everywhere in code is model.phi[1] and not  model.phi[d] 

### ISSUE THREAD

**Issue by ValeriiBaidin** [ericproffitt/TopicModelsVB.jl#32]
Hi. I am sorry to bother you.
I am wondering, why everywhere in code is model.phi[1] and not  model.phi[d].
Is it correct?

**Comment by ericproffitt** [comment]
Hi Valerii,

In order to significantly reduce the memory overhead of the model, I decided not to store each document's `phi` parameter. Thus `model.phi` is overwritten for each document.

If you want to recompute `phi` for a particular document `d`, you can run,

```julia
TopicModelsVB.update_phi!(model, d)
```

Then `model.phi[1]` will be the `phi` corresponding to document `d`.

**Comment by ValeriiBaidin** [comment]
> Hi Valerii,
> 
> In order to significantly reduce memory overhead, I decided not to store each document's `phi` parameter. Thus `model.phi` is overwritten for each document.
> 
> If you want to recompute `phi` for a particular document `d`, you can run,
> 
> ```julia
> TopicModelsVB.update_phi!(model, d)
> ```
> 
> Then `model.phi[1]` will be the `phi` corresponding to document `d`.

Oh. yes, I see it. 
It's just because, you didn't need to keep it for each document. 

SO why in this case, do you have vector of Phi. Is it just from the previous version?

**Comment by ericproffitt** [comment]
I forget the exact reason why I kept it as a vector, but it basically led to a more elegant code architecture.

**Comment by ValeriiBaidin** [comment]
So I worry, how phi[1] is matched length for all documents?

**Comment by ericproffitt** [comment]
It changes in size for different documents.

**Comment by ValeriiBaidin** [comment]
> It changes in size for different documents.

`model.phi[1] = model.beta[:,terms] .* exp.(model.Elogtheta[d])`

so if length(d) > length phi[1]?

**Comment by ericproffitt** [comment]
I'm not sure I understand your question.

`phi` is just a vector which contains a single element, that element is switched out for each document.

so if you have 4 topics, and `length(doc1)=10`, then

```julia
terms = model.corp[1].terms
model.phi[1] = model.beta[:,terms] .* exp.(model.Elogtheta[1])
```

`model.phi[1]` will be a matrix of size 4 x 10.

Then if doc2 has 20 terms, then

```julia
terms = model.corp[2].terms
model.phi[2] = model.beta[:,terms] .* exp.(model.Elogtheta[2])
```

`model.phi[1]` will be a matrix of size 4 x 20.
