### ISSUE TITLE
Is it possible to use Int32 for docs.terms

### ISSUE THREAD

**Issue by ValeriiBaidin** [ericproffitt/TopicModelsVB.jl#33]
Is it possible to use Int32 for docs.terms
It will help to save memory. 

p.s. I think even int16 is enough. =))

I am sorry to bother you again. 
Thank you so much

**Comment by ValeriiBaidin** [comment]
> Is it possible to use Int32 for docs.terms
> It will help to save memory.
> 
> p.s. I think even int16 is enough. =))
> 
> I am sorry to bother you again.
> Thank you so much

I did it by myself. I hope it helps to save memory.

**Comment by ValeriiBaidin** [comment]
Would you help, how to change doc.count to Int16
I will help to save 75% space. 

Where I have to change code. I have a problem with buffer.

**Comment by ericproffitt** [comment]
Hi Valerii,

So for the gpuLDA model, if you're changing both `doc.terms` and `doc.counts` to `Int16`, then you need to change lines 388 and 390 in `modelutils.jl` to,

```julia
model.terms_buffer = cl.Buffer(Int16, model.context, (:r, :copy), hostbuf=terms)
```

```julia
model.counts_buffer = cl.Buffer(Int16, model.context, (:r, :copy), hostbuf=counts)
```

**Comment by ericproffitt** [comment]
On a more general note,

I may look into defining `Int32` and `Int16` constructors for the Document and Corpus types. However I'll need to think some about how exactly this will work and any potential side effects before I actually make the changes.

**Comment by ValeriiBaidin** [comment]
I've done it for my uses right now (GPU)

Terms - Int32 
counts - Int16

It saves memory and I hope also increase speed.
