### ISSUE TITLE
Just to check my understanding. I don't need to check_elbo!() on each iteration, is it right?

### ISSUE THREAD

**Issue by ValeriiBaidin** [ericproffitt/TopicModelsVB.jl#35]
Just to check my understanding. I don't need to check_elbo!() on each iteration, is it right?

**Comment by ericproffitt** [comment]
Correct, checking the elbo just lets you (and the algorithm) know when you're reaching a local optima.

**Comment by ValeriiBaidin** [comment]
> Correct, checking the elbo just lets you know when your algorithm is getting close to converging to a local optima.

Thank you. 
It's very time consuming. especially, when I have a lot of documents.
